// Bundles the report's client code (src/report/client/**) into src/report/dist/client.js, which
// report.js inlines into every HTML report. The bundle is committed so that `node bin/tecton.js`,
// the GitHub Action and the npm package all work without a build step or any runtime dependency.
//
//   node scripts/build.js           build once
//   node scripts/build.js --watch   rebuild on change (pair with `tecton serve` to see edits live)
//   node scripts/build.js --check   fail if the committed bundle is out of date (CI)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as esbuild from 'esbuild';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outfile = path.join(root, 'src', 'report', 'dist', 'client.js');
const mode = process.argv.includes('--watch') ? 'watch' : process.argv.includes('--check') ? 'check' : 'build';

/** @type {import('esbuild').BuildOptions} */
const options = {
  entryPoints: [path.join(root, 'src', 'report', 'client', 'main.js')],
  bundle: true,
  format: 'iife',
  target: 'es2020',
  minify: true,
  legalComments: 'none',
  charset: 'ascii', // escapes U+2028/2029 and other non-ASCII, so the bundle is safe inside <script>
  banner: { js: '// Generated by scripts/build.js from src/report/client/. Do not edit.' },
  logLevel: 'warning',
};

if (mode === 'watch') {
  const ctx = await esbuild.context({ ...options, outfile, logLevel: 'info' });
  await ctx.watch();
} else {
  const res = await esbuild.build({ ...options, write: false, outfile });
  const code = res.outputFiles[0].text;
  if (mode === 'check') {
    const current = fs.existsSync(outfile) ? fs.readFileSync(outfile, 'utf8') : '';
    if (current !== code) {
      console.error('src/report/dist/client.js is out of date: run `npm run build` and commit the result.');
      process.exit(1);
    }
    console.log('client bundle is up to date');
  } else {
    fs.mkdirSync(path.dirname(outfile), { recursive: true });
    fs.writeFileSync(outfile, code);
    console.log(`wrote ${path.relative(root, outfile)} (${(code.length / 1024).toFixed(1)} kB)`);
  }
}
